# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–

  Thank you and congrats ğŸ‰ for opening your very first issue in this project.
  AnitaB.org is an inclusive community, committed to creating a safe and positive environment.ğŸŒ¸ Please adhere to our [Code Of Conduct](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/code_of_conduct.md).ğŸ™ŒğŸ»

  You may submit a PR on the same if you like!
  Please follow our [Commit Message Style Guide](https://github.com/anitab-org/mentorship-backend/wiki/Commit-Message-Style-Guide) while sending PRs.
  If you want to report a bugğŸ, please follow our [bug_report.md](https://github.com/anitab-org/mentorship-backend/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) template.
  Also please make sure you include steps to reproduce it and be patient we will get back to you as soon as we can.ğŸ‘€


  Also feel free to join us on [AnitaB.org Open Source Zulip Community](https://anitab-org.zulipchat.com/).ğŸ¤ We have different streams for each active repo's for discussions.ğŸ‘©ğŸ»â€ğŸ’»ğŸ§‘ğŸ»â€ğŸ’»
  For mentorship-backend, join [#**mentorship-system>mentorship-backend**](https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system/topic/mentorship-backend)! Hope you have a great time here :)

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  Thank you and congrats ğŸ‰ for opening your first PR on this project.âœ¨
  Please ensure your Pull Request meets the [Commit Message Style Guide](https://github.com/anitab-org/mentorship-backend/wiki/Commit-Message-Style-Guide).
  We will review it soon! Until then you can check out the [`README.md`](../README.md) for more details on it.

  Moja-Global is an inclusive community, committed to creating a safe and positive environment.ğŸŒ¸ Please adhere to our [Code Of Conduct]().

  Incase you want to join us on [Moja-Global Open Source Slack]() , please drop an email [here](mailto:)
  Hope you have a great time here :)

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: |
  Wohoo!ğŸŠ Congrats on merging your first contribution to Moja-Global!âœ¨
  Your code is officially a part of Moja-Global now!! Time for a celebration ğŸ™ŒğŸ‰âš¡ï¸
  Feel free to explore more on this project.ğŸ¤—
  Join us on [AnitaB.org Open Source Zulip](https://anitab-org.zulipchat.com/).ğŸ¤ We have different streams for each active repo's for discussions.ğŸ‘©ğŸ»â€ğŸ’»ğŸ§‘ğŸ»â€ğŸ’»
  Do join our weekly check-in stream to share your weekly goals and the awesome work you did here.ğŸ˜ƒ

  <details>
  <summary><b>Now that you've completed this, you can help someone else take their first step!</b></summary>
  <p>Check out projects stream on Zulip and the `first-timer-only` issues to check if someone need help to figure out their problem or need some feedbacks.Reach out and be encouraging and friendly! ğŸ˜„ ğŸ‰</p>
  <p>People often get stuck at the same steps, so you might be able to help someone get unstuck, or help lead them to some documentation that'd help. Reach out and be encouraging and friendly! ğŸ˜„ ğŸ‰ </p>
  <p>Create a welcoming issue for someone else or review their pull requests! ğŸ˜„ ğŸ‰ </p>
  </details>


# It is recommended to include as many gifs and emojis as possible!
