language: python
sudo: required
python:
  - '3.6'
cache: pip
services:
  - docker
env:
  - IMAGE_NAME=mtreacy002/mentorship-backend
before_script:
 - chmod +x deploy.sh
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull "$IMAGE_NAME" || true
  - docker build --no-cache --tag "$IMAGE_NAME" .
  - python -m unittest discover tests -v
after_script:
  - docker images

before_deploy:
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: "$TRAVIS_REPO_SLUG"

after_success:
  - ./deploy.sh
