language: python
sudo: required
python:
  - '3.6'
cache: pip
before_script:
 - chmod +x deploy.sh
install:
  - pip3 install -r requirements.txt
script:
  - python -m unittest discover tests -v
  - pylint ./app --errors-only
after_success:
  - ./deploy.sh
