language: python
sudo: required
python:
  - '3.6'
cache: pip
before_script:
 - chmod +x deploy.sh
install:
  - pip3 install -r requirements.txt
  - pip3 install pylint
script:
  - python -m unittest discover tests -v
  - pylint ./app ./docs ./templates ./tests ./config.py ./run.py
after_success:
  - ./deploy.sh
